apiVersion: v1
data:
  index.html: |
    <!DOCTYPE HTML>
    <html>
      <head>
        <meta charset="UTF-8">
        <title>Examen 4 - Redes 2023-2</title>
        <link href="data:image/x-icon;base64," rel="icon" type="image/x-icon" />
      </head>
      <body>
        <h1>Hola</h1>
        <div>
          <p>Esta es la p치gina del <code>Equipo-AAR-ATDI-BME-DAAV-LMAM</code></p>
          <p>Nuestro dominio DNS es <code>waningnew.me</code></p>
          <ul>
            <li><em>Esta p치gina se est치 sirviendo desde el cluster de <b>Kubernetes</b> en <code>k3s.example.com</code></em></li>
          </ul>
        </div>
        <hr/>
        <code>Redes de Computadoras</code>
      </body>
    </html>
kind: ConfigMap
metadata:
  name: index-equipo-aar-atdi-bme-daav-lmam
  namespace: default
#Se eliminaron el TimeStamp, la versi칩n y el uid